name: freewill_fx_widgets
description: Custom widgets for FreewillFx Co., Ltd.
version: 0.0.4
homepage: https://github.com/rung-fx/freewill_fx_widgets

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^4.0.6
  package_info_plus: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
