name: freewill_fx_widgets
description: Custom widgets for FreewillFx Co., Ltd.
version: 1.4.11
homepage: https://github.com/rung-fx/freewill_fx_widgets

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  device_info_plus: ^11.2.1
  package_info_plus: ^8.1.3
  permission_handler: ^11.3.1
  camera: ^0.11.0+2
  image_picker: ^1.0.7
  image_cropper: ^8.1.0
  badges: ^3.1.1
  flutter_keyboard_visibility: ^6.0.0
  syncfusion_flutter_datepicker: ^28.1.41
  open_store: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
